language: scala

jdk: openjdk8

scala:
   - 2.13.3

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: tag IS present AND NOT fork

jobs:
  include:
    - stage: test
      script: sbt test
    - stage: release
      script: echo "Release 1"
      script: sbt version

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

